import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components import web_server_base
from esphome.components.web_server_base import CONF_WEB_SERVER_BASE_ID
from esphome.const import (
    CONF_DISABLED,
    CONF_ESPHOME,
    CONF_ID,
    CONF_OFFSET,
    CONF_OTA,
    CONF_PLATFORM,
    CONF_SIZE,
)
from esphome.core import CORE
import esphome.final_validate as fv
from esphome.helpers import write_file_if_changed

from .eboot_v1_data import EBOOT_V1_SECTOR

DEPENDENCIES = ["esp8266", "web_server"]
AUTO_LOAD = ["web_server_base"]

CONF_IROM_VMA = "irom_vma"
CONF_IROM_SIZE = "irom_size"
CONF_FLASH_SIZE = "flash_size"
CONF_SLOTS = "slots"
CONF_OTA_ID = "ota_id"
CONF_AUTO_CONVERT = "auto_convert"
CONF_SAFE_MODE = "safe_mode"

migration_ns = cg.esphome_ns.namespace("esp8266_nonos_v2_to_eboot_v1")
Esp8266NonosV2ToEbootV1 = migration_ns.class_(
    "Esp8266NonosV2ToEbootV1", cg.Component
)

SLOT_SCHEMA = cv.Schema(
    {
        cv.Required(CONF_OFFSET): cv.positive_int,
        cv.Required(CONF_SIZE): cv.positive_int,
    }
)


def _validate_layout(config):
    slots = sorted(config[CONF_SLOTS], key=lambda slot: slot[CONF_OFFSET])
    if len(slots) != 2:
        raise cv.Invalid("ESP8266 non-OS layout requires exactly two slots")
    previous_end = 0
    for slot in slots:
        offset = slot[CONF_OFFSET]
        end = offset + slot[CONF_SIZE]
        if offset < previous_end:
            raise cv.Invalid("slot ranges overlap")
        if end > config[CONF_FLASH_SIZE]:
            raise cv.Invalid("slot range exceeds flash_size")
        previous_end = end
    config[CONF_SLOTS] = slots
    return config


def _optional_ota_id(value):
    # Imported lazily so a profile without native OTA does not pay the import.
    from esphome.components.esphome.ota import ESPHomeOTAComponent

    return cv.use_id(ESPHomeOTAComponent)(value)


CONFIG_SCHEMA = cv.All(
    cv.Schema(
        {
            cv.GenerateID(): cv.declare_id(Esp8266NonosV2ToEbootV1),
            cv.GenerateID(CONF_WEB_SERVER_BASE_ID): cv.use_id(
                web_server_base.WebServerBase
            ),
            cv.Required(CONF_FLASH_SIZE): cv.positive_int,
            cv.Required(CONF_SLOTS): cv.ensure_list(SLOT_SCHEMA),
            cv.Required(CONF_IROM_VMA): cv.positive_int,
            cv.Required(CONF_IROM_SIZE): cv.positive_int,
            # Convert on the first upper-slot boot; relocation is slot
            # control's own automatic option.
            cv.Optional(CONF_AUTO_CONVERT, default=False): cv.boolean,
            # Optional native OTA component; its setup is suppressed while the
            # V2 layout is still active.
            cv.Optional(CONF_OTA_ID): _optional_ota_id,
        }
    ).extend(cv.COMPONENT_SCHEMA),
    _validate_layout,
)


def _final_validate(config):
    full_config = fv.full_config.get()
    if any(
        entry.get(CONF_PLATFORM) == CONF_ESPHOME
        for entry in full_config.get(CONF_OTA, [])
    ) and CONF_OTA_ID not in config:
        raise cv.Invalid(
            f"wire '{CONF_OTA_ID}' to the '{CONF_OTA}: platform: {CONF_ESPHOME}' "
            "instance so the OTA listener is suppressed while the V2 layout is "
            "active"
        )
    # Safe mode runs setup before this component is constructed, so the native
    # OTA listener would bind under the vendor layout without the gate.
    if not full_config.get(CONF_SAFE_MODE, {}).get(CONF_DISABLED, False):
        raise cv.Invalid(
            f"add '{CONF_SAFE_MODE}: {CONF_DISABLED}: true' to a transition "
            "profile: ESPHome starts the native OTA listener in safe mode before "
            "this component can suppress it"
        )


FINAL_VALIDATE_SCHEMA = _final_validate


def _linker_script(config) -> str:
    """Link the application for the eboot V1 layout, reserving the flash tail.

    The IROM mapping must match the eboot application load address, and the
    filesystem/parameter pointers are pinned past the reserved PHY/calibration
    tail so the application never overwrites it.
    """
    irom_vma = config[CONF_IROM_VMA]
    irom_size = config[CONF_IROM_SIZE]
    return f"""/* Generated by esp8266_nonos_v2_to_eboot_v1. */
MEMORY
{{
  dport0_0_seg : org = 0x3FF00000, len = 0x10
  dram0_0_seg  : org = 0x3FFE8000, len = 0x14000
  irom0_0_seg  : org = 0x{irom_vma:08X}, len = 0x{irom_size:X}
}}
PROVIDE ( _FS_start = 0x403FB000 );
PROVIDE ( _FS_end = 0x403FB000 );
PROVIDE ( _FS_page = 0x0 );
PROVIDE ( _FS_block = 0x0 );
PROVIDE ( _EEPROM_start = 0x403FB000 );
PROVIDE ( _SPIFFS_start = 0x403FB000 );
PROVIDE ( _SPIFFS_end = 0x403FB000 );
PROVIDE ( _SPIFFS_page = 0x0 );
PROVIDE ( _SPIFFS_block = 0x0 );
INCLUDE "local.eagle.app.v6.common.ld"
"""


def _render_eboot_header(sector: bytes) -> str:
    if len(sector) != 0x1000:
        raise cv.Invalid("embedded eboot sector must be 4096 bytes")
    lines = ["#pragma once", "", "#include <cstdint>", "", "static const uint8_t EBOOT_V1_SECTOR[4096] = {"]
    for offset in range(0, len(sector), 16):
        chunk = ", ".join(f"0x{byte:02X}" for byte in sector[offset : offset + 16])
        lines.append(f"  {chunk},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


async def to_code(config):
    server = await cg.get_variable(config[CONF_WEB_SERVER_BASE_ID])
    var = cg.new_Pvariable(config[CONF_ID], server)
    await cg.register_component(var, config)
    cg.add(var.set_flash_size(config[CONF_FLASH_SIZE]))
    cg.add(var.set_irom_range(config[CONF_IROM_VMA], config[CONF_IROM_SIZE]))
    cg.add(var.set_auto_convert(config[CONF_AUTO_CONVERT]))
    for index, slot in enumerate(config[CONF_SLOTS]):
        cg.add(var.set_slot(index, slot[CONF_OFFSET], slot[CONF_SIZE]))
    if (ota_id := config.get(CONF_OTA_ID)) is not None:
        ota = await cg.get_variable(ota_id)
        cg.add(var.set_native_ota(ota))

    linker_script = CORE.relative_build_path("esp8266-nonos-v2-to-eboot-v1.ld")
    linker_script.parent.mkdir(parents=True, exist_ok=True)
    write_file_if_changed(linker_script, _linker_script(config))
    cg.add_platformio_option("board_build.ldscript", str(linker_script))

    header = CORE.relative_build_path("self_convert_eboot.h")
    write_file_if_changed(header, _render_eboot_header(EBOOT_V1_SECTOR))
    cg.add_build_flag(f"-I{header.parent}")
