import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components import web_server_base
from esphome.components.web_server_base import CONF_WEB_SERVER_BASE_ID
from esphome.const import CONF_ID, CONF_OFFSET, CONF_SIZE
from esphome.core import CORE
from esphome.helpers import write_file_if_changed
import esphome.final_validate as fv

DEPENDENCIES = ["esp8266", "web_server"]
AUTO_LOAD = ["web_server_base"]

CONF_IROM_VMA = "irom_vma"
CONF_IROM_SIZE = "irom_size"
CONF_FLASH_SIZE = "flash_size"
CONF_SLOTS = "slots"

migration_ns = cg.esphome_ns.namespace("esp8266_nonos_v2_to_eboot_v1")
Esp8266NonosV2ToEbootV1 = migration_ns.class_(
    "Esp8266NonosV2ToEbootV1", cg.Component
)

SLOT_SCHEMA = cv.Schema(
    {cv.Required(CONF_OFFSET): cv.positive_int, cv.Required(CONF_SIZE): cv.positive_int}
)


def _validate_layout(config):
    slots = sorted(config[CONF_SLOTS], key=lambda slot: slot[CONF_OFFSET])
    if len(slots) != 2:
        raise cv.Invalid("ESP8266 non-OS layout requires exactly two slots")
    previous_end = 0
    for slot in slots:
        offset = slot[CONF_OFFSET]
        end = offset + slot[CONF_SIZE]
        if offset < previous_end:
            raise cv.Invalid("slot ranges overlap")
        if end > config[CONF_FLASH_SIZE]:
            raise cv.Invalid("slot range exceeds flash_size")
        previous_end = end
    config[CONF_SLOTS] = slots
    return config

CONFIG_SCHEMA = cv.All(
    cv.Schema(
        {
            cv.GenerateID(): cv.declare_id(Esp8266NonosV2ToEbootV1),
            cv.GenerateID(CONF_WEB_SERVER_BASE_ID): cv.use_id(
                web_server_base.WebServerBase
            ),
            cv.Required(CONF_FLASH_SIZE): cv.positive_int,
            cv.Required(CONF_SLOTS): cv.ensure_list(SLOT_SCHEMA),
            cv.Required(CONF_IROM_VMA): cv.positive_int,
            cv.Required(CONF_IROM_SIZE): cv.positive_int,
        }
    ).extend(cv.COMPONENT_SCHEMA),
    _validate_layout,
)


def _final_validate(config):
    full_config = fv.full_config.get()
    web_server = full_config.get("web_server", {})
    if "auth" not in web_server:
        raise cv.Invalid(
            "esp8266_nonos_v2_to_eboot_v1 requires authenticated web_server access"
        )
    return config


FINAL_VALIDATE_SCHEMA = _final_validate


def _linker_script(config) -> str:
    irom_vma = config[CONF_IROM_VMA]
    irom_size = config[CONF_IROM_SIZE]
    return f"""/* Generated by esp8266_nonos_v2_to_eboot_v1. */
MEMORY
{{
  dport0_0_seg : org = 0x3FF00000, len = 0x10
  dram0_0_seg  : org = 0x3FFE8000, len = 0x14000
  irom0_0_seg  : org = 0x{irom_vma:08X}, len = 0x{irom_size:X}
}}
PROVIDE ( _FS_start = 0x403FB000 );
PROVIDE ( _FS_end = 0x403FB000 );
PROVIDE ( _FS_page = 0x0 );
PROVIDE ( _FS_block = 0x0 );
PROVIDE ( _EEPROM_start = 0x403FB000 );
PROVIDE ( _SPIFFS_start = 0x403FB000 );
PROVIDE ( _SPIFFS_end = 0x403FB000 );
PROVIDE ( _SPIFFS_page = 0x0 );
PROVIDE ( _SPIFFS_block = 0x0 );
INCLUDE "local.eagle.app.v6.common.ld"
"""


async def to_code(config):
    server = await cg.get_variable(config[CONF_WEB_SERVER_BASE_ID])
    var = cg.new_Pvariable(config[CONF_ID], server)
    await cg.register_component(var, config)
    cg.add(var.set_flash_size(config[CONF_FLASH_SIZE]))
    cg.add(var.set_irom_range(config[CONF_IROM_VMA], config[CONF_IROM_SIZE]))
    for index, slot in enumerate(config[CONF_SLOTS]):
        cg.add(var.set_slot(index, slot[CONF_OFFSET], slot[CONF_SIZE]))

    linker_script = CORE.relative_build_path("esp8266-nonos-to-eboot.ld")
    linker_script.parent.mkdir(parents=True, exist_ok=True)
    write_file_if_changed(linker_script, _linker_script(config))
    cg.add_platformio_option("board_build.ldscript", str(linker_script))
