#include "esp8266_nonos_v2_to_eboot_v1.h"

#ifdef USE_ESP8266

#include "self_convert_eboot.h"  // generated by __init__.py from eboot_v1_data.py

#include <Esp.h>

#include <algorithm>
#include <cstdio>
#include <cstring>

extern "C" {
#include <spi_flash.h>
#include <user_interface.h>

// The application's IROM section boundaries, defined by the generated linker
// script. The V1 IROM segment length is _irom0_text_end - _irom0_text_start;
// taking it from the linker keeps the conversion independent of esptool's
// alignment padding, which varies with the linked .irom0.text length.
extern uint8_t _irom0_text_start[];
extern uint8_t _irom0_text_end[];
}

#include "esphome/core/application.h"
#include "esphome/core/log.h"

namespace esphome::esp8266_nonos_v2_to_eboot_v1 {

static const char *const TAG = "esp8266_nonos_v2_to_eboot_v1";
// Unique key for the RTC-backed conversion-request preference. RTC memory
// (in_flash=false) survives a software reset and is lost on power loss, which
// is the desired fail-closed behaviour.
static constexpr uint32_t CONVERSION_REQUEST_HASH = 0x7A2F1C33;
// Separate RTC key for the last conversion result, so a reboot can report why
// the previous attempt did not convert.
static constexpr uint32_t CONVERSION_RESULT_HASH = 0x5C11D0E2;

// `alignas` must precede `static`; writing it the other way is ignored.
// NOLINTNEXTLINE(cppcoreguidelines-avoid-non-const-global-variables)
alignas(uint32_t) static uint8_t g_sector[Esp8266NonosV2ToEbootV1::SECTOR_SIZE];

static void store_u32_le(uint8_t *data, uint32_t value) {
  data[0] = value & 0xFF;
  data[1] = (value >> 8) & 0xFF;
  data[2] = (value >> 16) & 0xFF;
  data[3] = (value >> 24) & 0xFF;
}

static uint32_t address_of(const uint8_t *symbol) { return reinterpret_cast<uint32_t>(symbol); }

uint32_t Esp8266NonosV2ToEbootV1::read_u32_le_(const uint8_t *data) {
  return static_cast<uint32_t>(data[0]) | (static_cast<uint32_t>(data[1]) << 8) | (static_cast<uint32_t>(data[2]) << 16) |
         (static_cast<uint32_t>(data[3]) << 24);
}

bool Esp8266NonosV2ToEbootV1::read_flash_(uint32_t offset, uint8_t *data, size_t len) {
  // Read one aligned, 4-byte-multiple block per ESP.flashRead() call rather than
  // one word at a time; the conversion reads several hundred KiB.
  alignas(uint32_t) uint8_t buffer[68];
  while (len != 0) {
    const uint32_t aligned = offset & ~3U;
    const size_t skip = offset - aligned;
    size_t span = std::min(skip + len, sizeof(buffer));
    span = (span + 3U) & ~static_cast<size_t>(3U);
    if (!ESP.flashRead(aligned, buffer, span))
      return false;
    const size_t copy = std::min(len, span - skip);
    memcpy(data, buffer + skip, copy);
    offset += copy;
    data += copy;
    len -= copy;
  }
  return true;
}

bool Esp8266NonosV2ToEbootV1::read_flash_block_(uint32_t offset, uint8_t *data, size_t len) {
  if (!read_flash_(offset, data, len))
    return false;
  App.feed_wdt();
  return true;
}

uint32_t Esp8266NonosV2ToEbootV1::eboot_crc32_update_(uint32_t crc, const uint8_t *data, size_t len) {
  for (size_t index = 0; index < len; index++) {
    for (uint8_t mask = 0x80; mask != 0; mask >>= 1) {
      const bool invert = ((crc & 0x80000000UL) != 0) != ((data[index] & mask) != 0);
      crc <<= 1;
      if (invert)
        crc ^= 0x04C11DB7UL;
    }
  }
  return crc;
}

uint32_t Esp8266NonosV2ToEbootV1::sdk_crc32_update_(uint32_t crc, const uint8_t *data, size_t len) {
  // Reflected CRC-32 (polynomial 0xEDB88320) as used by binascii.crc32.
  for (size_t index = 0; index < len; index++) {
    crc ^= data[index];
    for (uint8_t bit = 0; bit < 8; bit++)
      crc = (crc >> 1) ^ (crc & 1 ? 0xEDB88320UL : 0);
  }
  return crc;
}

int Esp8266NonosV2ToEbootV1::ram_region_(uint32_t vma, uint32_t size) {
  if (size == 0 || vma > UINT32_MAX - size)
    return -1;
  const uint32_t end = vma + size;
  if (vma >= 0x3FFE8000 && end <= 0x40000000)
    return 0;  // DRAM
  if (vma >= 0x40100000 && end <= 0x40108000)
    return 1;  // IRAM
  return -1;
}

void Esp8266NonosV2ToEbootV1::ensure_preferences_() {
  if (this->preferences_ready_)
    return;
  // RTC preference offsets are assigned in call order, so these two calls must
  // happen in the same order on every boot. This runs first in setup(), ahead
  // of every other component that allocates preferences.
  this->conversion_request_ = global_preferences->make_preference<uint32_t>(CONVERSION_REQUEST_HASH, false);
  this->result_pref_ = global_preferences->make_preference<uint32_t>(CONVERSION_RESULT_HASH, false);
  this->preferences_ready_ = true;
}

void Esp8266NonosV2ToEbootV1::store_result_(Result result) {
  this->ensure_preferences_();
  this->result_ = result;
  this->last_result_ = static_cast<uint8_t>(result);
  uint32_t value = this->last_result_;
  if (this->result_pref_.save(&value))
    global_preferences->sync();
}

void Esp8266NonosV2ToEbootV1::fail_(Result result) {
  this->store_result_(result);
  ESP_LOGE(TAG, "Transition failed: %s", result_name_(result));
}

const char *Esp8266NonosV2ToEbootV1::result_name_(Result result) {
  switch (result) {
    case Result::IDLE:
      return "idle";
    case Result::IN_PROGRESS:
      return "in_progress";
    case Result::SUCCESS:
      return "success";
    case Result::ALREADY_CONVERTED:
      return "already_converted";
    case Result::WRONG_FLASH_SIZE:
      return "wrong_flash_size";
    case Result::UPPER_SLOT_REQUIRED:
      return "upper_slot_required";
    case Result::NOT_A_V2_IMAGE:
      return "not_a_v2_image";
    case Result::V2_IMAGE_INVALID:
      return "v2_image_invalid";
    case Result::OUT_OF_BOUNDS:
      return "out_of_bounds";
    case Result::FLASH_WRITE_FAILED:
      return "flash_write_failed";
    case Result::FLASH_READ_FAILED:
      return "flash_read_failed";
    case Result::READBACK_FAILED:
      return "readback_failed";
    case Result::BOOTLOADER_WRITE_FAILED:
      return "bootloader_write_failed";
  }
  return "unknown";
}

void Esp8266NonosV2ToEbootV1::gate_native_ota_() {
  if (this->native_ota_ != nullptr) {
    ESP_LOGW(TAG, "Still running the V2 layout; keeping native OTA unavailable");
    this->native_ota_->mark_failed();
  }
}

bool Esp8266NonosV2ToEbootV1::layout_is_eboot_() const {
  // Structural check, independent of the embedded blob's exact bytes: parse
  // sector zero as an E9 image and treat it as eboot when its first segment
  // loads at or above eboot's IRAM base. The vendor boot_v1.x loads at
  // 0x40100000, so this distinguishes the two bootloaders.
  uint8_t header[8];
  if (!read_flash_(0, header, sizeof(header)) || header[0] != E9_MAGIC)
    return false;
  const uint8_t segment_count = header[1];
  if (segment_count == 0 || segment_count > 16)
    return false;
  uint8_t segment_header[8];
  if (!read_flash_(8, segment_header, sizeof(segment_header)))
    return false;
  const uint32_t vma = read_u32_le_(segment_header);
  const uint32_t size = read_u32_le_(segment_header + 4);
  // eboot's segments load at 0x4010F000; the vendor boot_v1.x at 0x40100000.
  return size > 0 && vma >= EBOOT_IRAM_BASE && vma < 0x40110000;
}

bool Esp8266NonosV2ToEbootV1::load_segments_(const Slot &slot) {
  uint8_t header[V2_IROM_PAYLOAD_OFFSET];
  if (!read_flash_(slot.offset, header, sizeof(header))) {
    this->fail_(Result::FLASH_READ_FAILED);
    return false;
  }
  if (header[0] != V2_MAGIC || header[1] != V2_MARKER) {
    this->fail_(Result::NOT_A_V2_IMAGE);
    return false;
  }
  this->entry_ = read_u32_le_(header + 4);
  this->v2_irom_size_ = read_u32_le_(header + 12);

  const uint32_t irom_start = address_of(_irom0_text_start);
  const uint32_t irom_length = address_of(_irom0_text_end) - irom_start;
  if (irom_length <= FACTORY_PATCH_SIZE || irom_length > this->v2_irom_size_) {
    this->fail_(Result::V2_IMAGE_INVALID);
    return false;
  }
  // The V1 IROM segment is the V2 IROM payload's first irom_length bytes, with
  // the first eight replaced by the size/CRC patch.
  this->segments_[0] = {irom_start, irom_length, slot.offset + V2_IROM_PAYLOAD_OFFSET, true};

  const uint32_t inner = slot.offset + V2_IROM_PAYLOAD_OFFSET + this->v2_irom_size_;
  uint8_t inner_header[8];
  if (!read_flash_(inner, inner_header, 8) || inner_header[0] != E9_MAGIC) {
    this->fail_(Result::V2_IMAGE_INVALID);
    return false;
  }
  const uint8_t count = inner_header[1];
  if (count == 0 || count > MAX_SEGMENTS - 1) {
    this->fail_(Result::V2_IMAGE_INVALID);
    return false;
  }
  const uint32_t slot_end = slot.offset + slot.size;
  uint32_t cursor = inner + 8;
  uint8_t checksum = 0xEF;
  uint8_t block[64];
  for (uint8_t index = 0; index < count; index++) {
    uint8_t segment_header[8];
    if (!read_flash_(cursor, segment_header, 8)) {
      this->fail_(Result::FLASH_READ_FAILED);
      return false;
    }
    const uint32_t vma = read_u32_le_(segment_header);
    const uint32_t size = read_u32_le_(segment_header + 4);
    cursor += 8;
    if (size == 0 || cursor > slot_end || size > slot_end - cursor || ram_region_(vma, size) < 0) {
      this->fail_(Result::V2_IMAGE_INVALID);
      return false;
    }
    // Reject overlap with earlier RAM segments.
    const uint32_t end = vma + size;
    for (uint8_t previous = 1; previous <= index; previous++) {
      const SegmentSource &other = this->segments_[previous];
      if (vma < other.vma + other.size && other.vma < end) {
        this->fail_(Result::V2_IMAGE_INVALID);
        return false;
      }
    }
    this->segments_[1 + index] = {vma, size, cursor, false};
    for (uint32_t offset = 0; offset < size;) {
      const size_t length = std::min(sizeof(block), static_cast<size_t>(size - offset));
      if (!read_flash_block_(cursor + offset, block, length)) {
        this->fail_(Result::FLASH_READ_FAILED);
        return false;
      }
      for (size_t byte = 0; byte < length; byte++)
        checksum ^= block[byte];
      offset += length;
    }
    cursor += size;
  }

  const uint32_t checksum_offset = cursor | 0x0F;
  uint8_t stored[5];
  if (!read_flash_(checksum_offset, stored, sizeof(stored)) || stored[0] != checksum) {
    this->fail_(Result::V2_IMAGE_INVALID);
    return false;
  }
  // Reject a corrupt source before anything is written: verify the stored SDK
  // CRC32 over the whole user-bin.
  uint32_t crc = 0xFFFFFFFF;
  for (uint32_t offset = slot.offset; offset < checksum_offset + 1;) {
    const size_t length = std::min(sizeof(block), static_cast<size_t>(checksum_offset + 1 - offset));
    if (!read_flash_block_(offset, block, length)) {
      this->fail_(Result::FLASH_READ_FAILED);
      return false;
    }
    crc = sdk_crc32_update_(crc, block, length);
    offset += length;
  }
  crc ^= 0xFFFFFFFF;
  const uint32_t expected = (crc & 0x80000000UL) ? (crc ^ 0xFFFFFFFFUL) : (crc + 1);
  if (read_u32_le_(stored + 1) != expected) {
    this->fail_(Result::V2_IMAGE_INVALID);
    return false;
  }

  this->segment_count_ = 1 + count;
  return true;
}

bool Esp8266NonosV2ToEbootV1::compute_app_layout_() {
  uint32_t total = 8;  // E9 header
  for (size_t index = 0; index < this->segment_count_; index++)
    total += 8 + this->segments_[index].size;
  this->checksum_offset_ = total | 0x0F;
  this->app_size_ = this->checksum_offset_ + 1;

  uint8_t checksum = 0xEF;
  uint8_t block[64];
  for (size_t index = 0; index < this->segment_count_; index++) {
    const SegmentSource &segment = this->segments_[index];
    for (uint32_t offset = 0; offset < segment.size;) {
      const size_t length = std::min(sizeof(block), static_cast<size_t>(segment.size - offset));
      if (!read_flash_block_(segment.source_offset + offset, block, length))
        return false;
      for (size_t byte = 0; byte < length; byte++) {
        if (segment.irom && offset + byte < FACTORY_PATCH_SIZE)
          continue;  // elf2bin's size/CRC patch is excluded from the checksum
        checksum ^= block[byte];
      }
      offset += length;
    }
  }
  this->app_checksum_ = checksum;
  return true;
}

uint8_t Esp8266NonosV2ToEbootV1::app_byte_(uint32_t offset) {
  if (offset >= this->app_size_)
    return 0xFF;
  if (offset < 8) {
    const uint8_t header[8] = {E9_MAGIC, static_cast<uint8_t>(this->segment_count_), this->flash_mode_,
                               this->flash_size_freq_, static_cast<uint8_t>(this->entry_),
                               static_cast<uint8_t>(this->entry_ >> 8), static_cast<uint8_t>(this->entry_ >> 16),
                               static_cast<uint8_t>(this->entry_ >> 24)};
    return header[offset];
  }
  uint32_t cursor = 8;
  for (size_t index = 0; index < this->segment_count_; index++) {
    const SegmentSource &segment = this->segments_[index];
    if (offset < cursor + 8) {
      uint8_t segment_header[8];
      store_u32_le(segment_header, segment.vma);
      store_u32_le(segment_header + 4, segment.size);
      return segment_header[offset - cursor];
    }
    cursor += 8;
    if (offset < cursor + segment.size) {
      const uint32_t relative = offset - cursor;
      if (segment.irom && relative < FACTORY_PATCH_SIZE)
        return 0x00;  // patched with size/CRC after the write pass
      const uint32_t source = segment.source_offset + relative;
      if (source < this->src_cache_offset_ || source >= this->src_cache_offset_ + this->src_cache_len_) {
        this->src_cache_offset_ = source;
        const uint32_t remaining = segment.source_offset + segment.size - source;
        this->src_cache_len_ = std::min(this->src_cache_.size(), static_cast<size_t>(remaining));
        if (!read_flash_block_(source, this->src_cache_.data(), this->src_cache_len_)) {
          this->src_cache_len_ = 0;
          this->fail_(Result::FLASH_READ_FAILED);
          return 0xFF;
        }
      }
      return this->src_cache_[source - this->src_cache_offset_];
    }
    cursor += segment.size;
  }
  if (offset == this->checksum_offset_)
    return this->app_checksum_;
  return 0x00;  // elf2bin pads with zeros up to the checksum
}

bool Esp8266NonosV2ToEbootV1::write_application_(uint32_t *app_size, uint32_t *factory_crc) {
  if (!this->compute_app_layout_()) {
    this->fail_(Result::FLASH_READ_FAILED);
    return false;
  }
  // The V1 factory image starts at flash zero and extends through the lower
  // slot. Refuse before any erase if it would reach the running upper slot.
  if (SECTOR_SIZE + this->app_size_ > this->slots_[1].offset) {
    this->fail_(Result::OUT_OF_BOUNDS);
    return false;
  }
  this->eboot_[2] = this->flash_mode_;
  this->eboot_[3] = this->flash_size_freq_;

  // CRC over the whole factory image with the size/CRC patch zeroed. app_byte_()
  // already returns zero for the IROM patch bytes.
  uint32_t crc = 0xFFFFFFFF;
  crc = eboot_crc32_update_(crc, this->eboot_.data(), SECTOR_SIZE);
  for (uint32_t offset = 0; offset < this->app_size_; offset++) {
    const uint8_t value = this->app_byte_(offset);
    crc = eboot_crc32_update_(crc, &value, 1);
    if (this->result_ == Result::FLASH_READ_FAILED)
      return false;
  }

  const uint32_t end = SECTOR_SIZE + this->app_size_;
  for (uint32_t address = SECTOR_SIZE; address < end; address += SECTOR_SIZE) {
    for (size_t index = 0; index < SECTOR_SIZE; index++) {
      const uint32_t relative = address - SECTOR_SIZE + index;
      g_sector[index] = relative < this->app_size_ ? this->app_byte_(relative) : 0xFF;
    }
    if (this->result_ == Result::FLASH_READ_FAILED)
      return false;
    if (spi_flash_erase_sector(address / SECTOR_SIZE) != SPI_FLASH_RESULT_OK ||
        spi_flash_write(address, reinterpret_cast<uint32_t *>(g_sector), SECTOR_SIZE) != SPI_FLASH_RESULT_OK) {
      this->fail_(Result::FLASH_WRITE_FAILED);
      return false;
    }
    App.feed_wdt();
  }

  // Patch the whole-image size and CRC into the first application sector.
  for (size_t index = 0; index < SECTOR_SIZE; index++)
    g_sector[index] = index < this->app_size_ ? this->app_byte_(index) : 0xFF;
  if (this->result_ == Result::FLASH_READ_FAILED)
    return false;
  store_u32_le(g_sector + (FACTORY_SIZE_OFFSET - SECTOR_SIZE), SECTOR_SIZE + this->app_size_);
  store_u32_le(g_sector + (FACTORY_CRC_OFFSET - SECTOR_SIZE), crc);
  if (spi_flash_erase_sector(1) != SPI_FLASH_RESULT_OK ||
      spi_flash_write(SECTOR_SIZE, reinterpret_cast<uint32_t *>(g_sector), SECTOR_SIZE) != SPI_FLASH_RESULT_OK) {
    this->fail_(Result::FLASH_WRITE_FAILED);
    return false;
  }

  *app_size = this->app_size_;
  *factory_crc = crc;
  return true;
}

bool Esp8266NonosV2ToEbootV1::verify_app_(uint32_t app_size, uint32_t factory_crc) const {
  uint8_t word[4];
  if (!read_flash_(FACTORY_SIZE_OFFSET, word, 4) || read_u32_le_(word) != SECTOR_SIZE + app_size)
    return false;
  if (!read_flash_(FACTORY_CRC_OFFSET, word, 4) || read_u32_le_(word) != factory_crc)
    return false;

  // Hash exactly the image bytes, not whole sectors: the trailing 0xFF of the
  // final partial sector is not part of the expected CRC.
  uint32_t crc = 0xFFFFFFFF;
  crc = eboot_crc32_update_(crc, this->eboot_.data(), SECTOR_SIZE);
  for (uint32_t offset = 0; offset < app_size;) {
    const size_t length = std::min(SECTOR_SIZE, static_cast<size_t>(app_size - offset));
    if (!read_flash_block_(SECTOR_SIZE + offset, g_sector, length))
      return false;
    if (offset == 0 && length >= FACTORY_PATCH_SIZE)
      memset(g_sector + (FACTORY_SIZE_OFFSET - SECTOR_SIZE), 0, FACTORY_PATCH_SIZE);
    crc = eboot_crc32_update_(crc, g_sector, length);
    offset += length;
  }
  return crc == factory_crc;
}

bool Esp8266NonosV2ToEbootV1::commit_bootloader_() {
  if (spi_flash_erase_sector(0) != SPI_FLASH_RESULT_OK ||
      spi_flash_write(0, reinterpret_cast<uint32_t *>(this->eboot_.data()), SECTOR_SIZE) != SPI_FLASH_RESULT_OK)
    return false;
  if (!read_flash_(0, g_sector, SECTOR_SIZE))
    return false;
  return memcmp(g_sector, this->eboot_.data(), SECTOR_SIZE) == 0;
}

void Esp8266NonosV2ToEbootV1::erase_stale_upper_slot_() {
  // Under eboot the running application is at 0x1000; the upper V2 slot may
  // still hold the pre-conversion Kickstart copy. Invalidate its header so a
  // stale copy can never be re-converted. It is already not bootable under
  // eboot, so this changes nothing functional.
  const Slot &upper = this->slots_[1];
  if (upper.offset <= SECTOR_SIZE)
    return;
  uint8_t magic[2];
  if (!read_flash_(upper.offset, magic, sizeof(magic)))
    return;
  if (magic[0] != V2_MAGIC || magic[1] != V2_MARKER)
    return;
  if (spi_flash_erase_sector(upper.offset / SECTOR_SIZE) == SPI_FLASH_RESULT_OK)
    ESP_LOGI(TAG, "Invalidated the stale V2 copy in the upper slot");
}

bool Esp8266NonosV2ToEbootV1::convert() {
  if (ESP.getFlashChipRealSize() != this->flash_size_) {
    this->fail_(Result::WRONG_FLASH_SIZE);
    return false;
  }
  // A V1 factory image starts at flash zero and extends through the lower V2
  // slot, so the bridge must run from the upper slot before converting. Lower
  // slot relocation is the caller's responsibility; converting in place would
  // overwrite the running code.
  const uint8_t current = system_upgrade_userbin_check();
  if (current != 1) {
    this->fail_(Result::UPPER_SLOT_REQUIRED);
    return false;
  }
  // The ROM reads the SPI mode from sector zero, the vendor bootloader the
  // device has already booted, so keep that mode. The size/map byte comes from
  // the eboot build: the vendor's 2 MB c1 code is a two-slot packaging
  // convention that does not describe the single-application eboot layout.
  uint8_t sector_zero[4];
  this->flash_size_freq_ = EBOOT_V1_SECTOR[3];
  const bool sector_zero_valid = read_flash_(0, sector_zero, sizeof(sector_zero)) && sector_zero[0] == E9_MAGIC;
  this->flash_mode_ = sector_zero_valid ? sector_zero[2] : EBOOT_V1_SECTOR[2];
  if (!this->load_segments_(this->slots_[1]))
    return false;
  uint32_t app_size = 0;
  uint32_t factory_crc = 0;
  if (!this->write_application_(&app_size, &factory_crc))
    return false;
  if (!this->verify_app_(app_size, factory_crc)) {
    this->fail_(Result::READBACK_FAILED);
    return false;
  }
  if (!this->commit_bootloader_()) {
    this->fail_(Result::BOOTLOADER_WRITE_FAILED);
    return false;
  }
  return true;
}

void Esp8266NonosV2ToEbootV1::setup() {
  this->server_->init();
  this->server_->add_handler(this);
  this->ensure_preferences_();

  uint32_t stored_result = 0;
  if (this->result_pref_.load(&stored_result)) {
    this->previous_result_ = static_cast<uint8_t>(stored_result);
    this->last_result_ = this->previous_result_;
  }

  uint32_t requested = 0;
  const bool conversion_requested =
      this->conversion_request_.load(&requested) && requested == CONVERSION_REQUEST_MAGIC;
  if (conversion_requested) {
    // Consume the request before converting so a reset mid-conversion lands in
    // a networked V2 Kickstarter instead of a retry loop.
    const uint32_t cleared = 0;
    this->conversion_request_.save(&cleared);
    global_preferences->sync();
  }

  std::copy(EBOOT_V1_SECTOR, EBOOT_V1_SECTOR + SECTOR_SIZE, this->eboot_.begin());

  if (this->layout_is_eboot_()) {
    this->converted_ = true;
    this->store_result_(Result::ALREADY_CONVERTED);
    ESP_LOGI(TAG, "Already running the eboot V1 layout");
    this->erase_stale_upper_slot_();
    return;  // ordinary OTA is valid on the eboot layout
  }

  if (conversion_requested) {
    if (this->attempt_conversion_())
      return;
  } else if (this->auto_convert_ && system_upgrade_userbin_check() == 1 && !this->conversion_attempted()) {
    // Automatic conversion only runs from the upper slot; relocation to it is
    // the slot-control component's own automatic option.
    if (this->attempt_conversion_())
      return;
  }

  // Still on the vendor layout (conversion disabled, failed, or unknown):
  // keep ordinary firmware upload paths unavailable until a later boot
  // positively establishes the eboot layout.
  this->gate_native_ota_();
}

bool Esp8266NonosV2ToEbootV1::attempt_conversion_() {
  // Persist an in-progress marker so a reset mid-conversion is visible.
  this->store_result_(Result::IN_PROGRESS);
  if (!this->convert())
    return false;
  this->converted_ = true;
  this->store_result_(Result::SUCCESS);
  ESP_LOGI(TAG, "Transition complete; rebooting into the eboot V1 layout");
  App.safe_reboot();
  return true;
}

bool Esp8266NonosV2ToEbootV1::canHandle(AsyncWebServerRequest *request) const {
  return request->url() == CONVERSION_PATH &&
         (request->method() == HTTP_POST || request->method() == HTTP_GET);
}

void Esp8266NonosV2ToEbootV1::handleRequest(AsyncWebServerRequest *request) {
  if (request->url() != CONVERSION_PATH) {
    request->send(404, "application/json", "{\"error\":\"not_found\"}");
    return;
  }
  if (request->method() == HTTP_GET) {
    // Report both the persisted outcome from before this boot and this boot's.
    char body[160];
    snprintf(body, sizeof(body),
             "{\"previous_result\":\"%s\",\"previous_code\":%u,\"result\":\"%s\",\"code\":%u}",
             result_name_(static_cast<Result>(this->previous_result_)), static_cast<unsigned>(this->previous_result_),
             result_name_(this->result_), static_cast<unsigned>(this->result_));
    request->send(200, "application/json", body);
    return;
  }
  if (!request->hasParam("confirm") || request->getParam("confirm")->value() != CONVERSION_CONFIRMATION) {
    request->send(400, "application/json", "{\"error\":\"confirmation_required\"}");
    return;
  }
  if (this->layout_is_eboot_()) {
    request->send(409, "application/json", "{\"error\":\"already_converted\"}");
    return;
  }
  // A V1 factory image starts at flash zero and extends through the lower slot,
  // so converting from the lower slot would overwrite the running code. Reject
  // before rebooting instead of failing with upper_slot_required afterwards.
  if (system_upgrade_userbin_check() != 1) {
    request->send(409, "application/json", "{\"error\":\"upper_slot_required\"}");
    return;
  }
  request->send(202, "application/json", "{\"status\":\"conversion_requested\"}");
  // Defer out of the ESPAsyncWebServer callback so the response flushes first.
  this->set_timeout("conversion-request", 500, [this]() { this->request_conversion(); });
}

bool Esp8266NonosV2ToEbootV1::request_conversion() {
  this->ensure_preferences_();
  const uint32_t requested = CONVERSION_REQUEST_MAGIC;
  if (!this->conversion_request_.save(&requested)) {
    ESP_LOGE(TAG, "Could not persist the conversion request");
    return false;
  }
  global_preferences->sync();
  ESP_LOGI(TAG, "Conversion requested; rebooting to convert before Wi-Fi");
  App.safe_reboot();
  return true;
}

void Esp8266NonosV2ToEbootV1::dump_config() {
  ESP_LOGCONFIG(TAG, "ESP8266 non-OS V2 to eboot V1 transition:");
  ESP_LOGCONFIG(TAG, "  Flash size: %u", this->flash_size_);
  ESP_LOGCONFIG(TAG, "  IROM VMA: 0x%08X size: 0x%X", this->irom_address_, this->irom_size_);
  ESP_LOGCONFIG(TAG, "  Result: %s", result_name_(this->result_));
}

}  // namespace esphome::esp8266_nonos_v2_to_eboot_v1

#endif  // USE_ESP8266
