import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.core import CORE
from esphome.helpers import write_file_if_changed

DEPENDENCIES = ["esp8266"]
CONF_IROM_VMA = "irom_vma"
CONF_IROM_SIZE = "irom_size"
CONFIG_SCHEMA = cv.Schema(
    {
        cv.Required(CONF_IROM_VMA): cv.positive_int,
        cv.Required(CONF_IROM_SIZE): cv.positive_int,
    }
)


def _linker_script(config) -> str:
    irom_vma = config[CONF_IROM_VMA]
    irom_size = config[CONF_IROM_SIZE]
    return f"""/* Generated by kickstart_transition. */
MEMORY
{{
  dport0_0_seg : org = 0x3FF00000, len = 0x10
  dram0_0_seg  : org = 0x3FFE8000, len = 0x14000
  irom0_0_seg  : org = 0x{irom_vma:08X}, len = 0x{irom_size:X}
}}
PROVIDE ( _FS_start = 0x403FB000 );
PROVIDE ( _FS_end = 0x403FB000 );
PROVIDE ( _FS_page = 0x0 );
PROVIDE ( _FS_block = 0x0 );
PROVIDE ( _EEPROM_start = 0x403FB000 );
PROVIDE ( _SPIFFS_start = 0x403FB000 );
PROVIDE ( _SPIFFS_end = 0x403FB000 );
PROVIDE ( _SPIFFS_page = 0x0 );
PROVIDE ( _SPIFFS_block = 0x0 );
INCLUDE "local.eagle.app.v6.common.ld"
"""


async def to_code(config):
    linker_script = CORE.relative_build_path("kickstart-transition.ld")
    linker_script.parent.mkdir(parents=True, exist_ok=True)
    write_file_if_changed(linker_script, _linker_script(config))
    cg.add_platformio_option("board_build.ldscript", str(linker_script))
