#!/usr/bin/env python3
"""Extract the eboot V1 bootloader sector for the transition component.

The first 0x1000 bytes of any ESPHome/Arduino ESP8266 ``firmware.bin`` are the
eboot bootloader image (an E9 image of ``eboot.elf`` padded with 0xAA). The
sector is independent of the application, so it can be embedded once and reused
by the ``esp8266_nonos_v2_to_eboot_v1`` component when it rebuilds its own
application as an eboot V1 image.

Usage::

    python3 tools/generate_eboot_v1.py \
        --firmware-bin .pioenvs/<name>/firmware.bin \
        --output components/esp8266_nonos_v2_to_eboot_v1/eboot_v1_data.py
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

SECTOR_SIZE = 0x1000


def extract_sector(firmware_bin: Path) -> bytes:
    data = firmware_bin.read_bytes()
    if len(data) < SECTOR_SIZE or data[0] != 0xE9:
        raise ValueError(f"{firmware_bin} is not a V1 factory image (missing E9 bootloader)")
    return data[:SECTOR_SIZE]


def render_module(sector: bytes, source: str) -> str:
    hex_bytes = sector.hex()
    digest = hashlib.sha256(sector).hexdigest()
    lines = [
        '"""Generated by tools/generate_eboot_v1.py. Do not edit by hand.',
        "",
        f"Source: {source}",
        f"SHA-256: {digest}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "EBOOT_V1_SECTOR_SHA256 = " + repr(digest),
        "EBOOT_V1_SECTOR = bytes.fromhex(",
    ]
    for offset in range(0, len(hex_bytes), 128):
        lines.append("    " + repr(hex_bytes[offset : offset + 128]))
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--firmware-bin", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    sector = extract_sector(args.firmware_bin)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_module(sector, str(args.firmware_bin)), encoding="utf8")
    print(f"Wrote {len(sector)} bytes to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
